version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      atlas_run_migrations:
        condition: service_completed_successfully
  atlas_run_migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    volumes:
      - ./ent/migrate:/app/ent/migrate
      - ./ent/schema:/app/ent/schema
    entrypoint:
      - "atlas"
      - "migrate"
      - "apply"
      - "--dir"
      - "file://ent/migrate/migrations"
      - "--url"
      - "mysql://mysql:mysql@db:3306/discorddata"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: harbor.nicleary.com/dockerhub/mariadb
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: discorddata
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MARIADB_MYSQL_LOCALHOST_USER: 1
      MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 1s
      timeout: 2s
      retries: 3


volumes:
  mariadb_data:
