apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate-{{ now | unixEpoch }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  # Auto delete job to allow us to update it with subsequent deployments
  ttlSecondsAfterFinished: {{ .Values.migration.job.ttl }}
  template:
    metadata:
      name: "{{ .Release.Name }}-create-tables"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ .Values.migration.job.name }}-job
          image: {{ .Values.migration.job.container.image }}:{{ .Values.migration.job.container.tag }}
          command:
            - "atlas"
            - "migrate"
            - "apply"
            - "--dir"
            - "file://ent/migrate/migrations"
            - "--url"
            - "mysql://{{ .Values.db.user }}:{{ .Values.db.pass }}@{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.database_name }}"
      restartPolicy: Never
  backoffLimit: 4