apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.migration.job.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.migration.job.name }}-job
          image: {{ .Values.migration.job.container.image }}:{{ .Values.migration.job.container.tag }}
          command:
            - "atlas"
            - "migrate"
            - "apply"
            - "--dir"
            - "file://ent/migrate/migrations"
            - "--url"
            - "mysql://$MARIA_USER:$MARIA_PASS@$MARIA_HOST:$MARIA_PORT/$MARIA_DB"
          env:
            - name: "MARIA_USER"
              value: {{ .Values.db.user }}
            - name: "MARIA_HOST"
              value: {{ .Values.db.host }}
            - name: "MARIA_PORT"
              value: {{ .Values.db.port | quote }}
            - name: "MARIA_DB"
              value: {{ .Values.db.database_name }}
            - name: "MARIA_PASS"
              valueFrom:
                secretKeyRef:
                  name: "mariadb"
                  key: "mariadb-password"
      restartPolicy: Never
  backoffLimit: 4