name: "Main Action"

on:
  pull_request:
  workflow_dispatch:

jobs:

  build-api:
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.nicleary.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Docker build
        run: docker build -t harbor.nicleary.com/library/discord-metrics-server-api:${{ github.run_number }} -f Dockerfile .

      - name: Tag docker image
        run: docker tag harbor.nicleary.com/library/discord-metrics-server-api:${{ github.run_number }} harbor.nicleary.com/library/discord-metrics-server-api:latest

      - name: Push to harbor
        run: docker push harbor.nicleary.com/library/discord-metrics-server-api:latest && docker push harbor.nicleary.com/library/discord-metrics-server-api:${{ github.run_number }}

  build-migrations:
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.nicleary.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Docker build
        run: docker build -t harbor.nicleary.com/library/discord-metrics-server-migrations:${{ github.run_number }} -f Dockerfile .

      - name: Tag docker image
        run: docker tag harbor.nicleary.com/library/discord-metrics-server-migrations:${{ github.run_number }} harbor.nicleary.com/library/discord-metrics-server-migrations:latest

      - name: Push to harbor
        run: docker push harbor.nicleary.com/library/discord-metrics-server-migrations:latest && docker push harbor.nicleary.com/library/discord-metrics-server-migrations:${{ github.run_number }}

  trivy-api:
    needs: build-api
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker pull
        run: docker pull harbor.nicleary.com/library/discord-metrics-server-api:${{ github.run_number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'harbor.nicleary.com/library/discord-metrics-server-api:${{ github.run_number }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  trivy-migrations:
    needs: build-migrations
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker pull
        run: docker pull harbor.nicleary.com/library/discord-metrics-server-migrations:${{ github.run_number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'harbor.nicleary.com/library/discord-metrics-server-migrations:${{ github.run_number }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  codeql:
    needs:
      - build-api
      - build-migrations
    name: Analyze
    runs-on: nicleary-ubuntu-k8s
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

